test_that("log, exp, and cos are correct", {
  set.seed(1L)
  x = rnorm(10)
  y = abs(x)
  z = runif(10, 0, 1)
  expect_equal(matrix(exp(x)), engine_eval(~exp(x), x = x))
  expect_equal(matrix(log(y)), engine_eval(~log(y), y = y))
  expect_equal(matrix(cos(y)), engine_eval(~cos(y), y = y))
  expect_equal(matrix(sin(y)), engine_eval(~sin(y), y = y))
  expect_equal(matrix(plogis(y)), engine_eval(~invlogit(y), y = y))
  expect_equal(matrix(qlogis(z)), engine_eval(~logit(z), z = z))
})
