#' Describe Statistical Effects
#' 
#' Additional information that can be joined to the output of 
#' the `tidy.TMB` or `tidy.stanfit` functions in the `broom.mixed` package.
#' 
#' @param model A model in the TMB engine that can be used to compute 
#' tables of statistical effects.
#' @export
mp_effects_descr = function(model) UseMethod("mp_effects_descr")

#' @export
mp_effects_descr.TMBModel = function(model) {
  params = model$params$data_frame()
  random = model$random$data_frame()
  descr = bind_rows( ## see frame_utils.R
      params = params[, names(params) != "par_id", drop = FALSE]
    , random = random[, names(random) != "par_id", drop = FALSE]
    , .id = "term"
  )
  
  ## FIXME: fragile -- assumes that broom.mixed (or broom??) will continue
  ## to make term names unique.
  descr$term = make.unique(descr$term)
  descr
}

#' @export
mp_effects_descr.TMBSimulator = function(model) {
  mp_effects_descr(model$tmb_model)
}

#' @export
mp_effects_descr.TMBCalibrator = function(model) {
  mp_effects_descr(model$simulator)
}

#' @param coef_table Coefficient table that was probably generated using 
#' \code{\link{mp_tmb_coef}} or \code{\link{mp_tmbstan_coef}},
#' but also perhaps generated directly using the `tidy.TMB` or the 
#' `tidy.stanfit` methods in the `broom.mixed` package.
#' @describeIn mp_effects_descr Convenience function for adding coefficient
#' descriptions from a calibrated model to `coef_table`s generated by
#' \code{\link{mp_tmb_coef}} or \code{\link{mp_tmbstan_coef}}.
mp_add_effects_descr = function(coef_table, model) {
  descr = mp_effects_descr(model)
  if (!"term" %in% names(coef_table)) {
    stop("Cannot merge coefficient table with description")
  }
  bind_rows(
      merge(descr, filter(coef_table, startsWith(term, "params")))
    , merge(descr, filter(coef_table, startsWith(term, "random")))
    , filter(coef_table, !startsWith(term, "params") & !startsWith(term, "random"))
  )
}


#' TMB Model Coefficient Table
#'
#' @param model Object that contains information about model coefficients.
#' @param ... Arguments to pass onto the `broom.mixed::tidy.TMB` method.
#' @returns A data frame that describes the fitted coefficients.
#' @export
mp_tmb_coef = function(model, ...) UseMethod("mp_tmb_coef")

#' @export
mp_tmb_coef.TMBSimulator = function(model, ...) {
  assert_dependency("broom.mixed")
  tab = mp_add_effects_descr(broom.mixed::tidy(mp_tmb(model), ...), model)
  tab
}

#' @export
mp_tmb_coef.TMBCalibrator = function(model, ...) {
  mp_tmb_coef(model$simulator, ...)
}

#' Model Coefficient Table with stan
#' 
#' Leverages the \code{tmbstan} and \code{broom.mixed} packages to generate 
#' MCMC-based coefficient tables.
#' 
#' @inheritParams mp_tmb_coef
#' @param tmbstan_args Arguments to pass on to `tmbstan`, which is used to 
#' generate an `rstan` object from the underlying `TMB` object.
#' @param ... Arguments to pass onto the `broom.mixed::tidy.stanfit` method.
#' @export
mp_tmbstan_coef = function(model, tmbstan_args = list(), ...) UseMethod("mp_tmbstan_coef")

#' @export
mp_tmbstan_coef.TMBSimulator = function(model, tmbstan_args = list(), ...) {
  assert_dependencies("tmbstan", "broom.mixed")
  
  mp_add_effects_descr(broom.mixed::tidy(mp_tmb(model), ...), model)
  ad_fun = mp_tmb(model)
  stanfit = do.call(tmbstan::tmbstan, c(list(ad_fun), tmbstan_args))
  mp_add_effects_descr(broom.mixed::tidy(stanfit, ...), model)
}

#' @export
mp_tmbstan_coef.TMBCalibrator = function(model, tmbstan_args = list(), ...) {
  mp_tmbstan_coef(model$simulator, ...)
}


#' Covariance of Fixed Effect Estimates
#' 
#' @param model Object that contains information about fitted model parameters.
#' @returns A covariance matrix.
#' @export
mp_tmb_fixef_cov = function(model) UseMethod("mp_tmb_fixef_cov")

#' @export
mp_tmb_fixef_cov.TMBSimulator = function(model) {
  nms = mp_effects_descr(model)$mat
  cov_mat = model$cov.fixed()
  dimnames(cov_mat) = list(nms, nms)
  cov_mat
}

#' @export
mp_tmb_fixef_cov.TMBCalibrator = function(model) mp_tmb_fixef_cov(model$simulator)
  